### ISSUE TITLE
Flaky test : manager invitation

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#3412]
![Screenshot 2024-01-09 at 17-15-29 Retours d'Arthur · betagouv_ma-cantine@fcb5cce](https://github.com/betagouv/ma-cantine/assets/9282816/74220df5-9a77-46d9-b20f-90bb472ea154)

encountered on commit https://github.com/betagouv/ma-cantine/pull/3408/commits/fcb5cceda74d350360eefe052723766c0d52da81

**Comment by qloridant** [comment]
Même problème, mais avec des mails différents :
(aujourd'hui sur staging, bug 'résolu' en relançant les tests

```
 ======================================================================
FAIL: test_authenticated_create_manager_invitation (api.tests.test_manager_invitations.TestManagerInvitationApi)
When calling this API authenticated we expect to save the
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/ma-cantine/ma-cantine/api/tests/utils.py", line 13, in authenticate_and_func
    return func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/django/test/utils.py", line 461, in inner
    return func(*args, **kwargs)
  File "/home/runner/work/ma-cantine/ma-cantine/api/tests/test_manager_invitations.py", line 94, in test_authenticated_create_manager_invitation
    self.assertEqual(body["managers"][0]["email"], authenticate.user.email)
AssertionError: 'flemonnier@example.com' != 'davidadele@example.net'
- flemonnier@example.com
+ davidadele@example.net


----------------------------------------------------------------------
```

**Comment by qloridant** [comment]
Je crois que j'ai trouvé le problème.

Dans la [Factory d'une Canteen](https://github.com/betagouv/ma-cantine/blob/f39b172fc0ac26b2e98042dbdd0cf1f23073add2/data/factories/canteen.py#L36), qui est appelé dans le test, on a un nombre aléatoire de Managers crées (entre 1 et 2). Je crois que c'est pas très robuste de faire ça dans une factory.

Du coup, parfois on avait deux managers, et dans le test cela pose problème car nous allons récupérer le premier manager d'une liste, sans certitude de savoir c'est lequel `body["managers"][0]["email"]`

Bon, mon hypothèse expliquerait pourquoi ça marche que 3 fois sur 4, et ce depuis un an. Or le pbm vient d'apparaître...
@hfroot , @alemangui est-ce que vous vous souvenez pourquoi cette [création aléatoire d'une liste de manager avait été implémentée](d70db9376216d85a25eeb0d2211c2cde5c1ad3bb) ?

**Comment by qloridant** [comment]
Je crois que j'ai trouvé le problème.

Dans la [Factory d'une Canteen](https://github.com/betagouv/ma-cantine/blob/f39b172fc0ac26b2e98042dbdd0cf1f23073add2/data/factories/canteen.py#L36), qui est appelé dans le test, on a un nombre aléatoire de Managers crées (entre 1 et 2). Je crois que c'est pas très robuste de faire ça dans une factory.

Du coup, parfois on avait deux managers, et dans le test cela pose problème car nous allons récupérer le premier manager d'une liste, sans certitude de savoir c'est lequel `body["managers"][0]["email"]`

Bon, mon hypothèse expliquerait pourquoi ça marche que 3 fois sur 4, et ce depuis un an. Or le pbm vient d'apparaître...
@hfroot , @alemangui est-ce que vous vous souvenez pourquoi cette [création aléatoire d'une liste de manager avait été implémentée](d70db9376216d85a25eeb0d2211c2cde5c1ad3bb) ?
