### ISSUE TITLE
MAJ test

### ISSUE THREAD

**Issue by hfroot** [betagouv/ma-cantine#883]
```
FAIL: test_error_collection (api.tests.test_import_diagnostics.TestImportDiagnosticsAPI)
If errors occur, discard the file and return the errors with row and message
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/requests_mock/mocker.py", line 275, in inner
    return func(*args, **kwargs)
  File "/home/runner/work/ma-cantine/ma-cantine/api/tests/utils.py", line 13, in authenticate_and_func
    return func(*args, **kwargs)
  File "/home/runner/work/ma-cantine/ma-cantine/api/tests/test_import_diagnostics.py", line 242, in test_error_collection
    self.assertEqual(
AssertionError: "Champ 'année' : L'année doit être comprise entre 2019 et 2023." != "Champ 'année' : L'année doit être comprise entre 2019 et 2022."
- Champ 'année' : L'année doit être comprise entre 2019 et 2023.
?                                                             ^
+ Champ 'année' : L'année doit être comprise entre 2019 et 2022.
```

**Comment by hfroot** [comment]
https://github.com/betagouv/ma-cantine/commit/64da08993449883e6490c8a6d5e7489bd81195e8
